services:
  postgresql:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres
    environment:
      POSTGRES_DB: test_postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data:rw
    restart: always  
volumes:
  postgresql_data:
    driver: local